/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ecrans;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfContentByte;
import com.lowagie.text.pdf.PdfTemplate;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.FileDialog;
import java.awt.Graphics2D;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.io.FileOutputStream;

/**
 *
 * @author Niakulu
 */
public class AjoutConvention extends javax.swing.JFrame {
    private final DefaultListModel clients;
    private final DefaultListModel etudiants;
    /**
     * Creates new form AjoutConvention
     */
    public AjoutConvention() {
        initComponents();
        this.setVisible(true);
        GraphicsEnvironment genv = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Rectangle bounds = genv.getMaximumWindowBounds();
        this.setBounds(bounds);
        clients = new DefaultListModel();
        etudiants= new DefaultListModel();
        remplirListeModels();
        jlistClients.setModel(clients);
        jlistEtudiants.setModel(etudiants);
        //remplir les listes avec les données de la bdd
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan_Menu = new javax.swing.JPanel();
        pan_Profil = new javax.swing.JPanel();
        lbl_NomUtilisateur = new javax.swing.JLabel();
        lbl_prenomUtilisateur = new javax.swing.JLabel();
        lbl_Img = new javax.swing.JLabel();
        pan_Nav = new javax.swing.JPanel();
        lbl_profil = new javax.swing.JLabel();
        lbl_accueil = new javax.swing.JLabel();
        lbl_suivi_mission = new javax.swing.JLabel();
        cbb_missions = new javax.swing.JComboBox<>();
        lbl_entreprise = new javax.swing.JLabel();
        cbb_entreprises = new javax.swing.JComboBox<>();
        lbl_etudiants = new javax.swing.JLabel();
        cbb_etudiants = new javax.swing.JComboBox<>();
        lbl_conventions = new javax.swing.JLabel();
        cbb_conventions = new javax.swing.JComboBox<>();
        lbl_facturation = new javax.swing.JLabel();
        cbb_facturation = new javax.swing.JComboBox<>();
        bt_Deco = new javax.swing.JButton();
        AjoutConvention = new javax.swing.JPanel();
        lb_entrepriseCliente = new javax.swing.JLabel();
        lb_choisirClient = new javax.swing.JLabel();
        lb_creerClient = new javax.swing.JLabel();
        lb_choisirEtudiant = new javax.swing.JLabel();
        lb_CreerEtudiant = new javax.swing.JLabel();
        lb_descriptionMission = new javax.swing.JLabel();
        jspDescription = new javax.swing.JScrollPane();
        ta_description = new javax.swing.JTextArea();
        bt_newClient = new javax.swing.JButton();
        bt_newEtudiant = new javax.swing.JButton();
        bt_enregistrerPDF = new javax.swing.JButton();
        bt_enregistrerBrouillion = new javax.swing.JButton();
        bt_annuler = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(3, 0), new java.awt.Dimension(3, 0), new java.awt.Dimension(3, 32767));
        jspListeClients = new javax.swing.JScrollPane();
        jlistClients = new javax.swing.JList<>();
        jspListeEtudiant = new javax.swing.JScrollPane();
        jlistEtudiants = new javax.swing.JList<>();
        tf_choixClient = new javax.swing.JTextField();
        tf_choixEtudiant = new javax.swing.JTextField();
        lb_choixClient = new javax.swing.JLabel();
        lb_choixEtudiant = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Unagi - Création de convention");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pan_Menu.setBackground(new java.awt.Color(220, 220, 220));
        pan_Menu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pan_Profil.setBackground(new java.awt.Color(255, 255, 255));
        pan_Profil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_NomUtilisateur.setText("lbl_NomUtilisateur");

        lbl_prenomUtilisateur.setText("lbl_prenomUtilisateur");

        lbl_Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/snake2.png"))); // NOI18N

        javax.swing.GroupLayout pan_ProfilLayout = new javax.swing.GroupLayout(pan_Profil);
        pan_Profil.setLayout(pan_ProfilLayout);
        pan_ProfilLayout.setHorizontalGroup(
            pan_ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_ProfilLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(lbl_Img)
                .addGroup(pan_ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_ProfilLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lbl_NomUtilisateur))
                    .addGroup(pan_ProfilLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbl_prenomUtilisateur)))
                .addGap(25, 25, 25))
        );
        pan_ProfilLayout.setVerticalGroup(
            pan_ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_ProfilLayout.createSequentialGroup()
                .addGroup(pan_ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pan_ProfilLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_Img))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pan_ProfilLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lbl_NomUtilisateur)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_prenomUtilisateur)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pan_Nav.setBackground(new java.awt.Color(255, 255, 255));
        pan_Nav.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pan_Nav.setPreferredSize(new java.awt.Dimension(300, 500));
        pan_Nav.setVerifyInputWhenFocusTarget(false);

        lbl_profil.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbl_profil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_profil.setText("Voir Profil");
        lbl_profil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_accueil.setBackground(new java.awt.Color(10, 10, 10));
        lbl_accueil.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbl_accueil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_accueil.setText("Accueil");
        lbl_accueil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_accueil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_accueilMouseClicked(evt);
            }
        });

        lbl_suivi_mission.setBackground(new java.awt.Color(10, 10, 10));
        lbl_suivi_mission.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbl_suivi_mission.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_suivi_mission.setText("Suivi Missions");
        lbl_suivi_mission.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_suivi_mission.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_suivi_missionMouseClicked(evt);
            }
        });

        cbb_missions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En cours", "Cloturées", "En attente" }));
        cbb_missions.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbb_missions.setVisible(false);
        cbb_missions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_missionsActionPerformed(evt);
            }
        });

        lbl_entreprise.setBackground(new java.awt.Color(10, 10, 10));
        lbl_entreprise.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbl_entreprise.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_entreprise.setText("Entreprises");
        lbl_entreprise.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_entreprise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_entrepriseMouseClicked(evt);
            }
        });

        cbb_entreprises.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Création", "Liste des entreprises" }));
        cbb_entreprises.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbb_entreprises.setVisible(false);
        cbb_entreprises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_entreprisesActionPerformed(evt);
            }
        });

        lbl_etudiants.setBackground(new java.awt.Color(10, 10, 10));
        lbl_etudiants.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbl_etudiants.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_etudiants.setText("Etudiants");
        lbl_etudiants.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_etudiants.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_etudiantsMouseClicked(evt);
            }
        });

        cbb_etudiants.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Création", "Liste des étudiants" }));
        cbb_etudiants.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbb_etudiants.setVisible(false);
        cbb_etudiants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_etudiantsActionPerformed(evt);
            }
        });

        lbl_conventions.setBackground(new java.awt.Color(10, 10, 10));
        lbl_conventions.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbl_conventions.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_conventions.setText("Conventions");
        lbl_conventions.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_conventions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_conventionsMouseClicked(evt);
            }
        });

        cbb_conventions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Création", "Brouillons", "Upload", "Liste des conventions" }));
        cbb_conventions.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbb_conventions.setVisible(false);
        cbb_conventions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_conventionsActionPerformed(evt);
            }
        });

        lbl_facturation.setBackground(new java.awt.Color(10, 10, 10));
        lbl_facturation.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbl_facturation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_facturation.setText("Facturation");
        lbl_facturation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_facturation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_facturationMouseClicked(evt);
            }
        });

        cbb_facturation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Création", "Brouillons", "Liste des factures" }));
        cbb_facturation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbb_facturation.setVisible(false);
        cbb_facturation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_facturationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan_NavLayout = new javax.swing.GroupLayout(pan_Nav);
        pan_Nav.setLayout(pan_NavLayout);
        pan_NavLayout.setHorizontalGroup(
            pan_NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_NavLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_NavLayout.createSequentialGroup()
                        .addGroup(pan_NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_conventions, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_facturation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(pan_NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbb_conventions, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbb_facturation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lbl_accueil, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pan_NavLayout.createSequentialGroup()
                        .addGroup(pan_NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_etudiants, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_entreprise, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                        .addGap(19, 19, 19)
                        .addGroup(pan_NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbb_entreprises, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbb_etudiants, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lbl_profil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pan_NavLayout.createSequentialGroup()
                        .addComponent(lbl_suivi_mission, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbb_missions, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pan_NavLayout.setVerticalGroup(
            pan_NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_NavLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_profil)
                .addGap(20, 20, 20)
                .addComponent(lbl_accueil)
                .addGap(18, 18, 18)
                .addGroup(pan_NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_suivi_mission)
                    .addComponent(cbb_missions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pan_NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_entreprise)
                    .addComponent(cbb_entreprises, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pan_NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_etudiants)
                    .addComponent(cbb_etudiants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pan_NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_conventions)
                    .addComponent(cbb_conventions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pan_NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_facturation)
                    .addComponent(cbb_facturation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(372, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pan_MenuLayout = new javax.swing.GroupLayout(pan_Menu);
        pan_Menu.setLayout(pan_MenuLayout);
        pan_MenuLayout.setHorizontalGroup(
            pan_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pan_Nav, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addComponent(pan_Profil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );
        pan_MenuLayout.setVerticalGroup(
            pan_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pan_Profil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pan_Nav, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                .addContainerGap())
        );

        bt_Deco.setBackground(new java.awt.Color(255, 51, 51));
        bt_Deco.setForeground(new java.awt.Color(255, 255, 255));
        bt_Deco.setText("Déconnexion");
        bt_Deco.setToolTipText("");
        bt_Deco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_DecoActionPerformed(evt);
            }
        });

        AjoutConvention.setBackground(new java.awt.Color(255, 255, 255));
        AjoutConvention.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lb_entrepriseCliente.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lb_entrepriseCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_entrepriseCliente.setText("Entreprise Cliente");
        lb_entrepriseCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lb_choisirClient.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lb_choisirClient.setText("Choisissez un client");

        lb_creerClient.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lb_creerClient.setText("Creer un nouveau client");

        lb_choisirEtudiant.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lb_choisirEtudiant.setText("Choisissez un etudiant");

        lb_CreerEtudiant.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lb_CreerEtudiant.setText("Creer un etudiant");

        lb_descriptionMission.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lb_descriptionMission.setText("Description Mission :");

        ta_description.setColumns(20);
        ta_description.setRows(5);
        ta_description.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jspDescription.setViewportView(ta_description);

        bt_newClient.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        bt_newClient.setText("Nouveau");
        bt_newClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_newClientActionPerformed(evt);
            }
        });

        bt_newEtudiant.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        bt_newEtudiant.setText("Nouveau");
        bt_newEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_newEtudiantActionPerformed(evt);
            }
        });

        bt_enregistrerPDF.setBackground(new java.awt.Color(0, 153, 0));
        bt_enregistrerPDF.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        bt_enregistrerPDF.setForeground(new java.awt.Color(255, 255, 255));
        bt_enregistrerPDF.setText("Enregistrer en PDF");
        bt_enregistrerPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enregistrerPDFActionPerformed(evt);
            }
        });

        bt_enregistrerBrouillion.setBackground(new java.awt.Color(255, 153, 0));
        bt_enregistrerBrouillion.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        bt_enregistrerBrouillion.setForeground(new java.awt.Color(255, 255, 255));
        bt_enregistrerBrouillion.setText("Enregistrer comme brouillon");
        bt_enregistrerBrouillion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enregistrerBrouillionActionPerformed(evt);
            }
        });

        bt_annuler.setBackground(new java.awt.Color(255, 51, 51));
        bt_annuler.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        bt_annuler.setForeground(new java.awt.Color(255, 255, 255));
        bt_annuler.setText("Annuler");
        bt_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_annulerActionPerformed(evt);
            }
        });

        jlistClients.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jlistClients.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jlistClients.setToolTipText("");
        jspListeClients.setViewportView(jlistClients);

        jlistEtudiants.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jspListeEtudiant.setViewportView(jlistEtudiants);

        tf_choixClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_choixClientActionPerformed(evt);
            }
        });

        tf_choixEtudiant.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tf_choixEtudiant.setToolTipText("");

        lb_choixClient.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lb_choixClient.setText("Votre choix :");

        lb_choixEtudiant.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lb_choixEtudiant.setText("Votre choix :");

        javax.swing.GroupLayout AjoutConventionLayout = new javax.swing.GroupLayout(AjoutConvention);
        AjoutConvention.setLayout(AjoutConventionLayout);
        AjoutConventionLayout.setHorizontalGroup(
            AjoutConventionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AjoutConventionLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(AjoutConventionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AjoutConventionLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(AjoutConventionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AjoutConventionLayout.createSequentialGroup()
                                .addComponent(lb_creerClient)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AjoutConventionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AjoutConventionLayout.createSequentialGroup()
                                        .addComponent(jspListeClients, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lb_choixClient)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_choixClient, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(bt_newClient))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(AjoutConventionLayout.createSequentialGroup()
                                .addComponent(bt_enregistrerPDF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_enregistrerBrouillion)
                                .addGap(119, 119, 119)
                                .addComponent(bt_annuler)
                                .addGap(42, 42, 42))))
                    .addGroup(AjoutConventionLayout.createSequentialGroup()
                        .addGroup(AjoutConventionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AjoutConventionLayout.createSequentialGroup()
                                .addGap(505, 505, 505)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AjoutConventionLayout.createSequentialGroup()
                                .addComponent(lb_CreerEtudiant)
                                .addGap(48, 48, 48)
                                .addGroup(AjoutConventionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt_newEtudiant)
                                    .addGroup(AjoutConventionLayout.createSequentialGroup()
                                        .addComponent(jspListeEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lb_choixEtudiant)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_choixEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lb_choisirEtudiant)
                            .addGroup(AjoutConventionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lb_choisirClient)
                                .addComponent(lb_entrepriseCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(AjoutConventionLayout.createSequentialGroup()
                        .addGroup(AjoutConventionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jspDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_descriptionMission, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 31, Short.MAX_VALUE))))
        );
        AjoutConventionLayout.setVerticalGroup(
            AjoutConventionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AjoutConventionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_entrepriseCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(AjoutConventionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AjoutConventionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jspListeClients, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AjoutConventionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AjoutConventionLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(AjoutConventionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lb_choixClient)
                                .addComponent(tf_choixClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(AjoutConventionLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(lb_choisirClient))))
                .addGap(18, 18, 18)
                .addGroup(AjoutConventionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AjoutConventionLayout.createSequentialGroup()
                        .addGroup(AjoutConventionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_newClient)
                            .addComponent(lb_creerClient))
                        .addGroup(AjoutConventionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AjoutConventionLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AjoutConventionLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(lb_choisirEtudiant))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AjoutConventionLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jspListeEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AjoutConventionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_choixEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_choixEtudiant)))
                .addGap(28, 28, 28)
                .addGroup(AjoutConventionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_CreerEtudiant)
                    .addComponent(bt_newEtudiant))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_descriptionMission, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(AjoutConventionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_enregistrerPDF)
                    .addComponent(bt_enregistrerBrouillion)
                    .addComponent(bt_annuler))
                .addGap(264, 264, 264))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pan_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AjoutConvention, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_Deco, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(bt_Deco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AjoutConvention, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_accueilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_accueilMouseClicked
        this.setVisible(false);
        AcceuilA acceuil = new AcceuilA();
        acceuil.setVisible(true);
    }//GEN-LAST:event_lbl_accueilMouseClicked

    private void lbl_suivi_missionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_suivi_missionMouseClicked

        if (!cbb_missions.isVisible()||cbb_entreprises.isVisible()||cbb_etudiants.isVisible()||cbb_conventions.isVisible()|| cbb_facturation.isVisible() ||cbb_entreprises.isVisible()){
            cbb_conventions.setVisible(false);
            cbb_entreprises.setVisible(false);
            cbb_etudiants.setVisible(false);
            cbb_facturation.setVisible(false);
            cbb_missions.setVisible(true);
        }
        else {
            cbb_conventions.setVisible(false);
            cbb_entreprises.setVisible(false);
            cbb_etudiants.setVisible(false);
            cbb_facturation.setVisible(false);
            cbb_missions.setVisible(false);
        }
    }//GEN-LAST:event_lbl_suivi_missionMouseClicked

    private void cbb_missionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_missionsActionPerformed
        String choix = (String) cbb_missions.getSelectedItem();
        if (choix.equals("En cours")){
            this.setVisible(false);
            SMission_EnCours encours = new SMission_EnCours();
            encours.setVisible(true);
        }
        if (choix.equals( "Cloturées")){
            this.setVisible(false);
            SMission_Cloturees cloture= new SMission_Cloturees();
            cloture.setVisible(true);
        }
        if (choix.equals("En attente")){
            this.setVisible(false);
            SMission_EnAttente attente= new SMission_EnAttente();
            attente.setVisible(true);
        }
    }//GEN-LAST:event_cbb_missionsActionPerformed

    private void lbl_entrepriseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_entrepriseMouseClicked

        if (!cbb_entreprises.isVisible()||cbb_etudiants.isVisible()||cbb_conventions.isVisible()|| cbb_facturation.isVisible() ||cbb_entreprises.isVisible()||cbb_missions.isVisible()){
            cbb_conventions.setVisible(false);
            cbb_entreprises.setVisible(true);
            cbb_etudiants.setVisible(false);
            cbb_facturation.setVisible(false);
            cbb_missions.setVisible(false);
        }
        else {
            cbb_conventions.setVisible(false);
            cbb_entreprises.setVisible(false);
            cbb_etudiants.setVisible(false);
            cbb_facturation.setVisible(false);
            cbb_missions.setVisible(false);
        }
    }//GEN-LAST:event_lbl_entrepriseMouseClicked

    private void cbb_entreprisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_entreprisesActionPerformed
        String choix = (String) cbb_entreprises.getSelectedItem();
        if (choix.equals("Création")){
            this.setVisible(false);
            AjoutClient ajoutC = new AjoutClient();
            ajoutC.setVisible(true);
        }
        if (choix.equals("Liste des entreprises")){
            this.setVisible(false);
            ListeClients listeC = new ListeClients();
            listeC.setVisible(true);
        }
    }//GEN-LAST:event_cbb_entreprisesActionPerformed

    private void lbl_etudiantsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_etudiantsMouseClicked

        if (!cbb_etudiants.isVisible()||cbb_conventions.isVisible()|| cbb_facturation.isVisible() ||cbb_entreprises.isVisible()||cbb_entreprises.isVisible()||cbb_missions.isVisible()){
            cbb_conventions.setVisible(false);
            cbb_entreprises.setVisible(false);
            cbb_etudiants.setVisible(true);
            cbb_facturation.setVisible(false);
            cbb_missions.setVisible(false);
        }
        else {
            cbb_conventions.setVisible(false);
            cbb_entreprises.setVisible(false);
            cbb_etudiants.setVisible(false);
            cbb_facturation.setVisible(false);
            cbb_missions.setVisible(false);
        }
    }//GEN-LAST:event_lbl_etudiantsMouseClicked

    private void cbb_etudiantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_etudiantsActionPerformed
        String choix = (String) cbb_etudiants.getSelectedItem();
        if (choix.equals("Création")){
            this.setVisible(false);
            AjoutEtudiant ajoutE = new AjoutEtudiant();
            ajoutE.setVisible(true);
        }
        if (choix.equals("Liste des étudiants")){
            this.setVisible(false);
            ListeEtudiants listeE = new ListeEtudiants();
            listeE.setVisible(true);
        }
    }//GEN-LAST:event_cbb_etudiantsActionPerformed

    private void lbl_conventionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_conventionsMouseClicked

        if (!cbb_conventions.isVisible()|| cbb_facturation.isVisible() || cbb_etudiants.isVisible()||cbb_entreprises.isVisible()||cbb_entreprises.isVisible()||cbb_missions.isVisible() ){
            cbb_conventions.setVisible(true);
            cbb_entreprises.setVisible(false);
            cbb_etudiants.setVisible(false);
            cbb_facturation.setVisible(false);
            cbb_missions.setVisible(false);
        }
        else {
            cbb_conventions.setVisible(false);
            cbb_entreprises.setVisible(false);
            cbb_etudiants.setVisible(false);
            cbb_facturation.setVisible(false);
            cbb_missions.setVisible(false);
        }
    }//GEN-LAST:event_lbl_conventionsMouseClicked

    private void cbb_conventionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_conventionsActionPerformed
        String choix = (String) cbb_conventions.getSelectedItem();
        if (choix.equals("Création")){
            this.setVisible(false);
            AjoutConvention ajoutC = new AjoutConvention();
            ajoutC.setVisible(true);
        }
        if (choix.equals("Brouillons")){
            this.setVisible(false);
            BrouillonsC brouillonC = new BrouillonsC();
            brouillonC.setVisible(true);
        }
        if (choix.equals("Upload")){
            this.setVisible(false);
            Upload upload = new Upload();
            upload.setVisible(true);
        }
        if (choix.equals("Liste des conventions")){
            this.setVisible(false);
            ListeConventionA listeC = new ListeConventionA();
            listeC.setVisible(true);
        }
    }//GEN-LAST:event_cbb_conventionsActionPerformed

    private void lbl_facturationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_facturationMouseClicked

        if (!cbb_facturation.isVisible() || cbb_conventions.isVisible() || cbb_etudiants.isVisible()||cbb_entreprises.isVisible()||cbb_entreprises.isVisible()||cbb_missions.isVisible() ){
            cbb_conventions.setVisible(false);
            cbb_entreprises.setVisible(false);
            cbb_etudiants.setVisible(false);
            cbb_facturation.setVisible(true);
            cbb_missions.setVisible(false);
        }
        else {
            cbb_conventions.setVisible(false);
            cbb_entreprises.setVisible(false);
            cbb_etudiants.setVisible(false);
            cbb_facturation.setVisible(true);
            cbb_missions.setVisible(false);
        }
    }//GEN-LAST:event_lbl_facturationMouseClicked

    private void cbb_facturationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_facturationActionPerformed
        String choix = (String) cbb_facturation.getSelectedItem();
        if (choix.equals("Création")){
            this.setVisible(false);
            AjoutFacture ajoutF = new AjoutFacture();
            ajoutF.setVisible(true);
        }
        if (choix.equals("Brouillons")){
            this.setVisible(false);
            BrouillonFacture brouillonF= new BrouillonFacture();
            brouillonF.setVisible(true);
        }
        if (choix.equals("Liste des factures")){
            this.setVisible(false);
            ListeFactures listeF = new ListeFactures();
            listeF.setVisible(true);
        }
    }//GEN-LAST:event_cbb_facturationActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       int input = JOptionPane.showConfirmDialog(this, "Voulez vous quitter l'application ?", "", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (input == JOptionPane.OK_OPTION) {
            System.out.println("Application Fermée");
            this.dispose();
            System.exit(0);
        } else if (input == JOptionPane.CANCEL_OPTION) {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void bt_DecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_DecoActionPerformed
        int input = JOptionPane.showConfirmDialog(this, "Voulez vous retourner à l'écran de connexion?", "", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (input == JOptionPane.OK_OPTION) {
            this.setVisible(false);
            Connexion connexion = new Connexion();
            connexion.setVisible(true);
        } else if (input == JOptionPane.CANCEL_OPTION) {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_bt_DecoActionPerformed

    private void bt_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_annulerActionPerformed
        // retourne sur la page d'accueil
        int input = JOptionPane.showConfirmDialog(this, "Voulez vous annuler l'édition de la convention? LES modifications apportées ne seront pas enregistrées?","Annuler", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (input == JOptionPane.OK_OPTION) {
            ta_description.setText("");

        } else if (input == JOptionPane.CANCEL_OPTION) {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_bt_annulerActionPerformed

    private void bt_enregistrerBrouillionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enregistrerBrouillionActionPerformed
        // enregistre les donnee entrees dans la formulaire dans la bdd
    }//GEN-LAST:event_bt_enregistrerBrouillionActionPerformed

    private void bt_enregistrerPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enregistrerPDFActionPerformed
        try {
            FileDialog fd = new FileDialog(this, "Choisissez un fichier", FileDialog.LOAD);
            fd.setDirectory("C:\\");
            fd.setFile("Unagi_Convention.pdf");
            fd.setVisible(true);
            String filename = fd.getFile();
            File fichier = new File(fd.getDirectory() + filename);
            Document doc = new Document();
            PdfWriter pdf = PdfWriter.getInstance(doc, new FileOutputStream(fichier));
            doc.open();
            doc.add(new Paragraph("Convention Unagi\n" +
"\n" +
"________________________________________\n" +
"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras turpis ex, volutpat vel quam at, volutpat varius dui. Maecenas facilisis mollis dolor, ac lacinia diam porttitor ac. Maecenas a odio cursus, consequat neque sed, pharetra velit. Duis eu justo justo. Duis magna ligula, tempor ac fermentum maximus, cursus nec mauris. Curabitur quis ornare urna. Suspendisse ullamcorper porttitor ex pretium ornare. Integer tristique sapien est, in bibendum eros semper ut. Duis sed justo aliquam, aliquet elit sed, posuere odio. Praesent vel bibendum erat, eu tempus tortor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam gravida vitae nibh in sagittis. Donec consequat hendrerit imperdiet. Duis a purus sit amet quam placerat rhoncus. Aenean tempor ut velit tempus ultricies.\n" +
"Donec gravida vestibulum sagittis. Phasellus ornare massa sed massa aliquet rhoncus eu sit amet est. Phasellus rutrum facilisis est vel blandit. Quisque cursus sed purus rutrum fringilla. Aenean et tincidunt ante. Nullam mi diam, lobortis ullamcorper posuere eget, eleifend a diam. Aliquam feugiat efficitur hendrerit. Etiam ultricies pulvinar aliquam. Vestibulum eget libero ac urna ullamcorper venenatis a non magna. In gravida congue est vitae rhoncus. Integer aliquet leo et feugiat imperdiet. Nulla facilisi. In congue odio dolor. Curabitur scelerisque vel nisl quis bibendum.\n" +
"Aenean porttitor odio dolor, id pretium enim dapibus ac. Sed dapibus gravida lorem in posuere. Morbi convallis lorem eget mauris commodo, id consequat libero dapibus. Ut sagittis odio vitae tellus congue, vel placerat lacus sagittis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nam ullamcorper orci a vestibulum volutpat. Sed vestibulum non turpis vel efficitur. Sed in lobortis ante. Nam non purus justo. Maecenas interdum bibendum quam ac accumsan. Aliquam magna elit, fermentum id auctor sit amet, pellentesque non risus. Nunc euismod ex mauris, nec porta lacus feugiat ut. Nullam mauris arcu, posuere ac justo ut, rhoncus scelerisque dolor. Etiam vestibulum at nulla eget commodo. Nam et ultrices urna, in interdum ipsum.\n" +
"Pellentesque at bibendum elit, sit amet tempor turpis. Pellentesque lacinia ipsum turpis, maximus viverra lorem malesuada id. Morbi tempus sed metus pulvinar facilisis. Curabitur nulla dui, placerat sed urna ornare, faucibus elementum lacus. Pellentesque hendrerit dui quis ipsum placerat aliquet. Suspendisse potenti. Donec a malesuada dolor.\n" +
"Aliquam et ante ligula. Ut nec dolor urna. Cras dictum ut purus fermentum maximus. Pellentesque mattis ut purus quis dignissim. Donec et auctor mi. Pellentesque ullamcorper at sapien vitae fringilla. Vestibulum ut ante convallis magna tempus luctus mollis at odio. Morbi ac placerat nibh, sit amet aliquet elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi justo magna, blandit at euismod quis, condimentum eget ligula."));

            doc.newPage();
            String client = (String) jlistClients.getSelectedValue();
            String etudiant = (String) jlistEtudiants.getSelectedValue();
            doc.add( new Paragraph("Le client :"+client));
            doc.add( new Paragraph("L'étudiant :"+etudiant));
            String description = ta_description.getText();
            doc.add( new Paragraph("Description de la mission :\n"+description));
            doc.close();
            Desktop.getDesktop().open(fichier);
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AjoutConvention.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(AjoutConvention.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AjoutConvention.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_enregistrerPDFActionPerformed

    private void bt_newClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_newClientActionPerformed
        this.setVisible(false);
        AjoutClient ajoutC = new AjoutClient();
        ajoutC.setVisible(true);        
    }//GEN-LAST:event_bt_newClientActionPerformed

    private void bt_newEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_newEtudiantActionPerformed
        this.setVisible(false);
        AjoutEtudiant ajoutE = new AjoutEtudiant();
        ajoutE.setVisible(true);
    }//GEN-LAST:event_bt_newEtudiantActionPerformed
    
    public void remplirListeModels()
    {
        
        /*clients.addElement();
        etudiants.addElement();*/
    }
    
    private void tf_choixClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_choixClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_choixClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutConvention.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutConvention.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutConvention.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutConvention.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjoutConvention().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AjoutConvention;
    private javax.swing.JButton bt_Deco;
    private javax.swing.JButton bt_annuler;
    private javax.swing.JButton bt_enregistrerBrouillion;
    private javax.swing.JButton bt_enregistrerPDF;
    private javax.swing.JButton bt_newClient;
    private javax.swing.JButton bt_newEtudiant;
    private javax.swing.JComboBox<String> cbb_conventions;
    private javax.swing.JComboBox<String> cbb_entreprises;
    private javax.swing.JComboBox<String> cbb_etudiants;
    private javax.swing.JComboBox<String> cbb_facturation;
    private javax.swing.JComboBox<String> cbb_missions;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JList<String> jlistClients;
    private javax.swing.JList<String> jlistEtudiants;
    private javax.swing.JScrollPane jspDescription;
    private javax.swing.JScrollPane jspListeClients;
    private javax.swing.JScrollPane jspListeEtudiant;
    private javax.swing.JLabel lb_CreerEtudiant;
    private javax.swing.JLabel lb_choisirClient;
    private javax.swing.JLabel lb_choisirEtudiant;
    private javax.swing.JLabel lb_choixClient;
    private javax.swing.JLabel lb_choixEtudiant;
    private javax.swing.JLabel lb_creerClient;
    private javax.swing.JLabel lb_descriptionMission;
    private javax.swing.JLabel lb_entrepriseCliente;
    private javax.swing.JLabel lbl_Img;
    private javax.swing.JLabel lbl_NomUtilisateur;
    private javax.swing.JLabel lbl_accueil;
    private javax.swing.JLabel lbl_conventions;
    private javax.swing.JLabel lbl_entreprise;
    private javax.swing.JLabel lbl_etudiants;
    private javax.swing.JLabel lbl_facturation;
    private javax.swing.JLabel lbl_prenomUtilisateur;
    private javax.swing.JLabel lbl_profil;
    private javax.swing.JLabel lbl_suivi_mission;
    private javax.swing.JPanel pan_Menu;
    private javax.swing.JPanel pan_Nav;
    private javax.swing.JPanel pan_Profil;
    private javax.swing.JTextArea ta_description;
    private javax.swing.JTextField tf_choixClient;
    private javax.swing.JTextField tf_choixEtudiant;
    // End of variables declaration//GEN-END:variables

        
       

    
}
