/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ecrans;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Niakulu
 */
public class ListeConventionsE extends javax.swing.JFrame {

    /**
     * Creates new form ListeCoventionsE
     */
    public ListeConventionsE() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan_Menu = new javax.swing.JPanel();
        pan_Profil = new javax.swing.JPanel();
        lbl_NomUtilisateur = new javax.swing.JLabel();
        lbl_prenomUtilisateur = new javax.swing.JLabel();
        lbl_Img = new javax.swing.JLabel();
        pan_Nav = new javax.swing.JPanel();
        lbl_profil = new javax.swing.JLabel();
        lbl_conventions = new javax.swing.JLabel();
        lbl_accueil = new javax.swing.JLabel();
        bt_Deco = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Unagi - Mes conventions");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pan_Menu.setBackground(new java.awt.Color(220, 220, 220));
        pan_Menu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pan_Profil.setBackground(new java.awt.Color(255, 255, 255));
        pan_Profil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_NomUtilisateur.setText("lbl_NomUtilisateur");

        lbl_prenomUtilisateur.setText("lbl_prenomUtilisateur");

        lbl_Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/snake2.png"))); // NOI18N

        javax.swing.GroupLayout pan_ProfilLayout = new javax.swing.GroupLayout(pan_Profil);
        pan_Profil.setLayout(pan_ProfilLayout);
        pan_ProfilLayout.setHorizontalGroup(
            pan_ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_ProfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Img)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pan_ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_prenomUtilisateur)
                    .addComponent(lbl_NomUtilisateur))
                .addContainerGap())
        );
        pan_ProfilLayout.setVerticalGroup(
            pan_ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_ProfilLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbl_NomUtilisateur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_prenomUtilisateur)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pan_ProfilLayout.createSequentialGroup()
                .addComponent(lbl_Img)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pan_Nav.setBackground(new java.awt.Color(255, 255, 255));
        pan_Nav.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pan_Nav.setPreferredSize(new java.awt.Dimension(300, 500));
        pan_Nav.setVerifyInputWhenFocusTarget(false);

        lbl_profil.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbl_profil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_profil.setText("Voir Profil");
        lbl_profil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_conventions.setBackground(new java.awt.Color(10, 10, 10));
        lbl_conventions.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbl_conventions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_conventions.setText("Conventions");
        lbl_conventions.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_conventions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_conventionsMouseClicked(evt);
            }
        });

        lbl_accueil.setBackground(new java.awt.Color(10, 10, 10));
        lbl_accueil.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbl_accueil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_accueil.setText("Accueil");
        lbl_accueil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_accueil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_accueilMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pan_NavLayout = new javax.swing.GroupLayout(pan_Nav);
        pan_Nav.setLayout(pan_NavLayout);
        pan_NavLayout.setHorizontalGroup(
            pan_NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_NavLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_profil, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(lbl_conventions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_accueil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pan_NavLayout.setVerticalGroup(
            pan_NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_NavLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_profil)
                .addGap(20, 20, 20)
                .addComponent(lbl_accueil)
                .addGap(28, 28, 28)
                .addComponent(lbl_conventions)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pan_MenuLayout = new javax.swing.GroupLayout(pan_Menu);
        pan_Menu.setLayout(pan_MenuLayout);
        pan_MenuLayout.setHorizontalGroup(
            pan_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_MenuLayout.createSequentialGroup()
                        .addComponent(pan_Profil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(13, 13, 13))
                    .addGroup(pan_MenuLayout.createSequentialGroup()
                        .addComponent(pan_Nav, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pan_MenuLayout.setVerticalGroup(
            pan_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pan_Profil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pan_Nav, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(317, Short.MAX_VALUE))
        );

        bt_Deco.setBackground(new java.awt.Color(255, 51, 51));
        bt_Deco.setForeground(new java.awt.Color(255, 255, 255));
        bt_Deco.setText("Déconnexion");
        bt_Deco.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pan_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 655, Short.MAX_VALUE)
                .addComponent(bt_Deco))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_Deco)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_conventionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_conventionsMouseClicked
        //A gérer avec la bd car on ne doit pouvoir afficher que les conventions qui concerne l'étudiant
    }//GEN-LAST:event_lbl_conventionsMouseClicked

    private void lbl_accueilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_accueilMouseClicked
        this.setVisible(false);
        AcceuilE acceuilE = new AcceuilE();
        acceuilE.setVisible(true);
    }//GEN-LAST:event_lbl_accueilMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int input = JOptionPane.showConfirmDialog(this, "Voulez vous quitter l'application ?", "", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (input == JOptionPane.OK_OPTION) {
            System.out.println("Application Fermée");
            this.dispose();
            System.exit(0);
        } else if (input == JOptionPane.CANCEL_OPTION) {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListeConventionsE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListeConventionsE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListeConventionsE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListeConventionsE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListeConventionsE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Deco;
    private javax.swing.JLabel lbl_Img;
    private javax.swing.JLabel lbl_NomUtilisateur;
    private javax.swing.JLabel lbl_accueil;
    private javax.swing.JLabel lbl_conventions;
    private javax.swing.JLabel lbl_prenomUtilisateur;
    private javax.swing.JLabel lbl_profil;
    private javax.swing.JPanel pan_Menu;
    private javax.swing.JPanel pan_Nav;
    private javax.swing.JPanel pan_Profil;
    // End of variables declaration//GEN-END:variables
}
