/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ecrans;

import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Niakulu
 */
public class SMission_EnCours extends javax.swing.JFrame {

    /**
     * Creates new form SMission_EnCours
     */
    public SMission_EnCours() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan_Menu3 = new javax.swing.JPanel();
        pan_Profil3 = new javax.swing.JPanel();
        lbl_NomUtilisateur3 = new javax.swing.JLabel();
        lbl_prenomUtilisateur3 = new javax.swing.JLabel();
        lbl_Img3 = new javax.swing.JLabel();
        pan_Nav1 = new javax.swing.JPanel();
        lbl_profil1 = new javax.swing.JLabel();
        lbl_accueil1 = new javax.swing.JLabel();
        lbl_suivi_mission1 = new javax.swing.JLabel();
        cbb_missions1 = new javax.swing.JComboBox<>();
        lbl_entreprise1 = new javax.swing.JLabel();
        cbb_entreprises1 = new javax.swing.JComboBox<>();
        lbl_etudiants1 = new javax.swing.JLabel();
        cbb_etudiants1 = new javax.swing.JComboBox<>();
        lbl_conventions1 = new javax.swing.JLabel();
        cbb_conventions1 = new javax.swing.JComboBox<>();
        lbl_facturation1 = new javax.swing.JLabel();
        cbb_facturation1 = new javax.swing.JComboBox<>();
        bt_Deco = new javax.swing.JButton();
        jpane_missions_en_cours = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable_missions_en_cours = new javax.swing.JTable();
        lbl_recherche = new javax.swing.JLabel();
        bt_valider = new javax.swing.JButton();
        txtField_recherche = new javax.swing.JTextField();
        jComboBox_enCours = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Unagi- Missions en cours");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pan_Menu3.setBackground(new java.awt.Color(220, 220, 220));
        pan_Menu3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pan_Profil3.setBackground(new java.awt.Color(255, 255, 255));
        pan_Profil3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_NomUtilisateur3.setText("lbl_NomUtilisateur");

        lbl_prenomUtilisateur3.setText("lbl_prenomUtilisateur");

        lbl_Img3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/snake2.png"))); // NOI18N

        javax.swing.GroupLayout pan_Profil3Layout = new javax.swing.GroupLayout(pan_Profil3);
        pan_Profil3.setLayout(pan_Profil3Layout);
        pan_Profil3Layout.setHorizontalGroup(
            pan_Profil3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_Profil3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(lbl_Img3)
                .addGroup(pan_Profil3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_Profil3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lbl_NomUtilisateur3))
                    .addGroup(pan_Profil3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbl_prenomUtilisateur3)))
                .addGap(25, 25, 25))
        );
        pan_Profil3Layout.setVerticalGroup(
            pan_Profil3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_Profil3Layout.createSequentialGroup()
                .addGroup(pan_Profil3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pan_Profil3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_Img3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pan_Profil3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lbl_NomUtilisateur3)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_prenomUtilisateur3)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pan_Nav1.setBackground(new java.awt.Color(255, 255, 255));
        pan_Nav1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pan_Nav1.setPreferredSize(new java.awt.Dimension(300, 500));
        pan_Nav1.setVerifyInputWhenFocusTarget(false);

        lbl_profil1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbl_profil1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_profil1.setText("Voir Profil");
        lbl_profil1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_accueil1.setBackground(new java.awt.Color(10, 10, 10));
        lbl_accueil1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbl_accueil1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_accueil1.setText("Accueil");
        lbl_accueil1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_accueil1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_accueil1MouseClicked(evt);
            }
        });

        lbl_suivi_mission1.setBackground(new java.awt.Color(10, 10, 10));
        lbl_suivi_mission1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbl_suivi_mission1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_suivi_mission1.setText("Suivi Missions");
        lbl_suivi_mission1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_suivi_mission1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_suivi_mission1MouseClicked(evt);
            }
        });

        cbb_missions1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En cours", "Cloturées", "En attente" }));
        cbb_missions1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbb_missions1.setVisible(false);
        cbb_missions1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_missions1ActionPerformed(evt);
            }
        });

        lbl_entreprise1.setBackground(new java.awt.Color(10, 10, 10));
        lbl_entreprise1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbl_entreprise1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_entreprise1.setText("Entreprises");
        lbl_entreprise1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_entreprise1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_entreprise1MouseClicked(evt);
            }
        });

        cbb_entreprises1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Création", "Liste des entreprises" }));
        cbb_entreprises1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbb_entreprises1.setVisible(false);
        cbb_entreprises1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_entreprises1ActionPerformed(evt);
            }
        });

        lbl_etudiants1.setBackground(new java.awt.Color(10, 10, 10));
        lbl_etudiants1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbl_etudiants1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_etudiants1.setText("Etudiants");
        lbl_etudiants1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_etudiants1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_etudiants1MouseClicked(evt);
            }
        });

        cbb_etudiants1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Création", "Liste des étudiants" }));
        cbb_etudiants1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbb_etudiants1.setVisible(false);
        cbb_etudiants1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_etudiants1ActionPerformed(evt);
            }
        });

        lbl_conventions1.setBackground(new java.awt.Color(10, 10, 10));
        lbl_conventions1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbl_conventions1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_conventions1.setText("Conventions");
        lbl_conventions1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_conventions1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_conventions1MouseClicked(evt);
            }
        });

        cbb_conventions1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Création", "Brouillons", "Upload", "Liste des conventions" }));
        cbb_conventions1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbb_conventions1.setVisible(false);
        cbb_conventions1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_conventions1ActionPerformed(evt);
            }
        });

        lbl_facturation1.setBackground(new java.awt.Color(10, 10, 10));
        lbl_facturation1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbl_facturation1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_facturation1.setText("Facturation");
        lbl_facturation1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_facturation1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_facturation1MouseClicked(evt);
            }
        });

        cbb_facturation1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Création", "Brouillons", "Liste des factures" }));
        cbb_facturation1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbb_facturation1.setVisible(false);
        cbb_facturation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_facturation1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan_Nav1Layout = new javax.swing.GroupLayout(pan_Nav1);
        pan_Nav1.setLayout(pan_Nav1Layout);
        pan_Nav1Layout.setHorizontalGroup(
            pan_Nav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_Nav1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_Nav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_Nav1Layout.createSequentialGroup()
                        .addGroup(pan_Nav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_conventions1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_facturation1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(pan_Nav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbb_conventions1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbb_facturation1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lbl_accueil1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pan_Nav1Layout.createSequentialGroup()
                        .addGroup(pan_Nav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_etudiants1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_entreprise1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                        .addGap(19, 19, 19)
                        .addGroup(pan_Nav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbb_entreprises1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbb_etudiants1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lbl_profil1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pan_Nav1Layout.createSequentialGroup()
                        .addComponent(lbl_suivi_mission1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbb_missions1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pan_Nav1Layout.setVerticalGroup(
            pan_Nav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_Nav1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_profil1)
                .addGap(20, 20, 20)
                .addComponent(lbl_accueil1)
                .addGap(18, 18, 18)
                .addGroup(pan_Nav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_suivi_mission1)
                    .addComponent(cbb_missions1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pan_Nav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_entreprise1)
                    .addComponent(cbb_entreprises1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pan_Nav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_etudiants1)
                    .addComponent(cbb_etudiants1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pan_Nav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_conventions1)
                    .addComponent(cbb_conventions1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pan_Nav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_facturation1)
                    .addComponent(cbb_facturation1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pan_Menu3Layout = new javax.swing.GroupLayout(pan_Menu3);
        pan_Menu3.setLayout(pan_Menu3Layout);
        pan_Menu3Layout.setHorizontalGroup(
            pan_Menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_Menu3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_Menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pan_Nav1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(pan_Profil3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );
        pan_Menu3Layout.setVerticalGroup(
            pan_Menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_Menu3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pan_Profil3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pan_Nav1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );

        bt_Deco.setBackground(new java.awt.Color(255, 51, 51));
        bt_Deco.setForeground(new java.awt.Color(255, 255, 255));
        bt_Deco.setText("Déconnexion");
        bt_Deco.setToolTipText("");

        jpane_missions_en_cours.setBackground(new java.awt.Color(255, 255, 255));
        jpane_missions_en_cours.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtable_missions_en_cours.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12)), "Liste desMissions en cours", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13))); // NOI18N
        jtable_missions_en_cours.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jtable_missions_en_cours.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Client", "Etudiant", "Annee", "Statut", "Convention", "Facture"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtable_missions_en_cours);

        lbl_recherche.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbl_recherche.setText("Recherche");

        bt_valider.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        bt_valider.setText("Valider");

        txtField_recherche.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtField_recherche.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtField_rechercheFocusGained(evt);
            }
        });

        jComboBox_enCours.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Par année", "Par Nom Client", "Par Nom Etudiant" }));
        jComboBox_enCours.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox_enCours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_enCoursActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpane_missions_en_coursLayout = new javax.swing.GroupLayout(jpane_missions_en_cours);
        jpane_missions_en_cours.setLayout(jpane_missions_en_coursLayout);
        jpane_missions_en_coursLayout.setHorizontalGroup(
            jpane_missions_en_coursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpane_missions_en_coursLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpane_missions_en_coursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                    .addGroup(jpane_missions_en_coursLayout.createSequentialGroup()
                        .addGroup(jpane_missions_en_coursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_recherche)
                            .addGroup(jpane_missions_en_coursLayout.createSequentialGroup()
                                .addComponent(jComboBox_enCours, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(txtField_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_valider)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpane_missions_en_coursLayout.setVerticalGroup(
            jpane_missions_en_coursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpane_missions_en_coursLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_recherche)
                .addGap(8, 8, 8)
                .addGroup(jpane_missions_en_coursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtField_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_valider)
                    .addComponent(jComboBox_enCours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pan_Menu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpane_missions_en_cours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14)
                .addComponent(bt_Deco))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan_Menu3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpane_missions_en_cours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_Deco)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_accueil1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_accueil1MouseClicked
        this.setVisible(false);
        AcceuilA acceuil = new AcceuilA();
        acceuil.setVisible(true);
    }//GEN-LAST:event_lbl_accueil1MouseClicked

    private void lbl_suivi_mission1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_suivi_mission1MouseClicked

        if (!cbb_missions1.isVisible()||cbb_entreprises1.isVisible()||cbb_etudiants1.isVisible()||cbb_conventions1.isVisible()|| cbb_facturation1.isVisible() ||cbb_entreprises1.isVisible()){
            cbb_conventions1.setVisible(false);
            cbb_entreprises1.setVisible(false);
            cbb_etudiants1.setVisible(false);
            cbb_facturation1.setVisible(false);
            cbb_missions1.setVisible(true);
        }
        else {
            cbb_conventions1.setVisible(false);
            cbb_entreprises1.setVisible(false);
            cbb_etudiants1.setVisible(false);
            cbb_facturation1.setVisible(false);
            cbb_missions1.setVisible(false);
        }
    }//GEN-LAST:event_lbl_suivi_mission1MouseClicked

    private void cbb_missions1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_missions1ActionPerformed
        String choix = (String) cbb_missions1.getSelectedItem();
        if (choix.equals("En cours")){
            this.setVisible(false);
            SMission_EnCours encours = new SMission_EnCours();
            encours.setVisible(true);
        }
        if (choix.equals( "Cloturées")){
            this.setVisible(false);
            SMission_Cloturees cloture= new SMission_Cloturees();
            cloture.setVisible(true);
        }
        if (choix.equals("En attente")){
            this.setVisible(false);
            SMission_EnAttente attente= new SMission_EnAttente();
            attente.setVisible(true);
        }
    }//GEN-LAST:event_cbb_missions1ActionPerformed

    private void lbl_entreprise1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_entreprise1MouseClicked

        if (!cbb_entreprises1.isVisible()||cbb_etudiants1.isVisible()||cbb_conventions1.isVisible()|| cbb_facturation1.isVisible() ||cbb_entreprises1.isVisible()||cbb_missions1.isVisible()){
            cbb_conventions1.setVisible(false);
            cbb_entreprises1.setVisible(true);
            cbb_etudiants1.setVisible(false);
            cbb_facturation1.setVisible(false);
            cbb_missions1.setVisible(false);
        }
        else {
            cbb_conventions1.setVisible(false);
            cbb_entreprises1.setVisible(false);
            cbb_etudiants1.setVisible(false);
            cbb_facturation1.setVisible(false);
            cbb_missions1.setVisible(false);
        }
    }//GEN-LAST:event_lbl_entreprise1MouseClicked

    private void cbb_entreprises1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_entreprises1ActionPerformed
        String choix = (String) cbb_entreprises1.getSelectedItem();
        if (choix.equals("Création")){
            this.setVisible(false);
            AjoutClient ajoutC = new AjoutClient();
            ajoutC.setVisible(true);
        }
        if (choix.equals("Liste des entreprises")){
            try {
                this.setVisible(false);
                ListeClients listeC = new ListeClients();
                listeC.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(SMission_EnCours.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cbb_entreprises1ActionPerformed

    private void lbl_etudiants1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_etudiants1MouseClicked

        if (!cbb_etudiants1.isVisible()||cbb_conventions1.isVisible()|| cbb_facturation1.isVisible() ||cbb_entreprises1.isVisible()||cbb_entreprises1.isVisible()||cbb_missions1.isVisible()){
            cbb_conventions1.setVisible(false);
            cbb_entreprises1.setVisible(false);
            cbb_etudiants1.setVisible(true);
            cbb_facturation1.setVisible(false);
            cbb_missions1.setVisible(false);
        }
        else {
            cbb_conventions1.setVisible(false);
            cbb_entreprises1.setVisible(false);
            cbb_etudiants1.setVisible(false);
            cbb_facturation1.setVisible(false);
            cbb_missions1.setVisible(false);
        }
    }//GEN-LAST:event_lbl_etudiants1MouseClicked

    private void cbb_etudiants1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_etudiants1ActionPerformed
        String choix = (String) cbb_etudiants1.getSelectedItem();
        if (choix.equals("Création")){
            this.setVisible(false);
            AjoutEtudiant ajoutE = new AjoutEtudiant();
            ajoutE.setVisible(true);
        }
        if (choix.equals("Liste des étudiants")){
            this.setVisible(false);
            ListeEtudiants listeE = null;
            try {
                listeE = new ListeEtudiants();
            } catch (SQLException ex) {
                Logger.getLogger(SMission_EnCours.class.getName()).log(Level.SEVERE, null, ex);
            }
            listeE.setVisible(true);
        }
    }//GEN-LAST:event_cbb_etudiants1ActionPerformed

    private void lbl_conventions1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_conventions1MouseClicked

        if (!cbb_conventions1.isVisible()|| cbb_facturation1.isVisible() || cbb_etudiants1.isVisible()||cbb_entreprises1.isVisible()||cbb_entreprises1.isVisible()||cbb_missions1.isVisible() ){
            cbb_conventions1.setVisible(true);
            cbb_entreprises1.setVisible(false);
            cbb_etudiants1.setVisible(false);
            cbb_facturation1.setVisible(false);
            cbb_missions1.setVisible(false);
        }
        else {
            cbb_conventions1.setVisible(false);
            cbb_entreprises1.setVisible(false);
            cbb_etudiants1.setVisible(false);
            cbb_facturation1.setVisible(false);
            cbb_missions1.setVisible(false);
        }
    }//GEN-LAST:event_lbl_conventions1MouseClicked

    private void cbb_conventions1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_conventions1ActionPerformed
        String choix = (String) cbb_conventions1.getSelectedItem();
        if (choix.equals("Création")){
            this.setVisible(false);
            AjoutConvention ajoutC = new AjoutConvention();
            ajoutC.setVisible(true);
        }
        if (choix.equals("Brouillons")){
            this.setVisible(false);
            BrouillonsC brouillonC = new BrouillonsC();
            brouillonC.setVisible(true);
        }
        if (choix.equals("Upload")){
            this.setVisible(false);
            Upload upload = new Upload();
            upload.setVisible(true);
        }
        if (choix.equals("Liste des conventions")){
            this.setVisible(false);
            ListeConventionA listeC = new ListeConventionA();
            listeC.setVisible(true);
        }
    }//GEN-LAST:event_cbb_conventions1ActionPerformed

    private void lbl_facturation1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_facturation1MouseClicked

        if (!cbb_facturation1.isVisible() || cbb_conventions1.isVisible() || cbb_etudiants1.isVisible()||cbb_entreprises1.isVisible()||cbb_entreprises1.isVisible()||cbb_missions1.isVisible() ){
            cbb_conventions1.setVisible(false);
            cbb_entreprises1.setVisible(false);
            cbb_etudiants1.setVisible(false);
            cbb_facturation1.setVisible(true);
            cbb_missions1.setVisible(false);
        }
        else {
            cbb_conventions1.setVisible(false);
            cbb_entreprises1.setVisible(false);
            cbb_etudiants1.setVisible(false);
            cbb_facturation1.setVisible(true);
            cbb_missions1.setVisible(false);
        }
    }//GEN-LAST:event_lbl_facturation1MouseClicked

    private void cbb_facturation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_facturation1ActionPerformed
        String choix = (String) cbb_facturation1.getSelectedItem();
        if (choix.equals("Création")){
            this.setVisible(false);
            AjoutFacture ajoutF = new AjoutFacture();
            ajoutF.setVisible(true);
        }
        if (choix.equals("Brouillons")){
            this.setVisible(false);
            BrouillonFacture brouillonF= new BrouillonFacture();
            brouillonF.setVisible(true);
        }
        if (choix.equals("Liste des factures")){
            this.setVisible(false);
            ListeFactures listeF = new ListeFactures();
            listeF.setVisible(true);
        }
    }//GEN-LAST:event_cbb_facturation1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
int input = JOptionPane.showConfirmDialog(this, "Voulez vous quitter l'application ?", "", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (input == JOptionPane.OK_OPTION) {
            System.out.println("Application Fermée");
            this.dispose();
            System.exit(0);
        } else if (input == JOptionPane.CANCEL_OPTION) {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void txtField_rechercheFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtField_rechercheFocusGained
        // TODO add your handling code here:
        txtField_recherche.setToolTipText("Entrez numero de mission");
    }//GEN-LAST:event_txtField_rechercheFocusGained

    private void jComboBox_enCoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_enCoursActionPerformed
        // TODO add your handling code here:
        String choix = (String) jComboBox_enCours.getSelectedItem();
        if (choix.equals("Par année")){
            //recup donnée BD
        }
        if (choix.equals("Par Nom Client")){
            //recup donnée BD
        }
        if (choix.equals("Par nom Etudiant")){
            //recup donnée BD
        }
    }//GEN-LAST:event_jComboBox_enCoursActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SMission_EnCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SMission_EnCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SMission_EnCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SMission_EnCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SMission_EnCours().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Deco;
    private javax.swing.JButton bt_valider;
    private javax.swing.JComboBox<String> cbb_conventions1;
    private javax.swing.JComboBox<String> cbb_entreprises1;
    private javax.swing.JComboBox<String> cbb_etudiants1;
    private javax.swing.JComboBox<String> cbb_facturation1;
    private javax.swing.JComboBox<String> cbb_missions1;
    private javax.swing.JComboBox<String> jComboBox_enCours;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpane_missions_en_cours;
    private javax.swing.JTable jtable_missions_en_cours;
    private javax.swing.JLabel lbl_Img3;
    private javax.swing.JLabel lbl_NomUtilisateur3;
    private javax.swing.JLabel lbl_accueil1;
    private javax.swing.JLabel lbl_conventions1;
    private javax.swing.JLabel lbl_entreprise1;
    private javax.swing.JLabel lbl_etudiants1;
    private javax.swing.JLabel lbl_facturation1;
    private javax.swing.JLabel lbl_prenomUtilisateur3;
    private javax.swing.JLabel lbl_profil1;
    private javax.swing.JLabel lbl_recherche;
    private javax.swing.JLabel lbl_suivi_mission1;
    private javax.swing.JPanel pan_Menu3;
    private javax.swing.JPanel pan_Nav1;
    private javax.swing.JPanel pan_Profil3;
    private javax.swing.JTextField txtField_recherche;
    // End of variables declaration//GEN-END:variables
}
