/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applisynth;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author carole
 */
public class CreationConvention extends javax.swing.JFrame {

    /**
     * Creates new form ListeConvention
     */
    public CreationConvention() {
        
        String[] listClients = {"cm1", "cm2", "cm3"};
        String[] listEtudiants = {"etu1", "etu2", "etu3"};
        
        modelCbbChoisirClient = new DefaultComboBoxModel<>();
        modelCbbChoisirEtudiant = new DefaultComboBoxModel<>();
        
        //on remplit chaque model de liste avec les valeurs du tableau de String correspondant
        for (String s : listClients) {
            modelCbbChoisirClient.addElement(s);
        }

        for (String s : listEtudiants) {
            modelCbbChoisirEtudiant.addElement(s);
        }       
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_main = new javax.swing.JPanel();
        lb_entrepriseCliente = new javax.swing.JLabel();
        lb_choisirClient = new javax.swing.JLabel();
        lb_creerClient = new javax.swing.JLabel();
        lb_choisirEtudiant = new javax.swing.JLabel();
        lb_CreerEtudiant = new javax.swing.JLabel();
        lb_descriptionMission = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        bt_newClient = new javax.swing.JButton();
        bt_newEtudiant = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        bt_enregistrerPDF = new javax.swing.JButton();
        bt_enregistrerBrouillion = new javax.swing.JButton();
        bt_annuler = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(3, 0), new java.awt.Dimension(3, 0), new java.awt.Dimension(3, 32767));
        bt_deconnexion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_main.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lb_entrepriseCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_entrepriseCliente.setText("Entreprise Cliente");
        lb_entrepriseCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lb_choisirClient.setText("Choisissez un client");

        lb_creerClient.setText("Creer un nouveau client");

        lb_choisirEtudiant.setText("Choisissez un etudiant");

        lb_CreerEtudiant.setText("Creer un etudiant");

        lb_descriptionMission.setText("Description Mission :");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        bt_newClient.setText("Nouveau");

        bt_newEtudiant.setText("Nouveau");

        jComboBox1.setModel(modelCbbChoisirClient);

        jComboBox2.setModel(modelCbbChoisirEtudiant);

        bt_enregistrerPDF.setText("Enregistrer en PDF");
        bt_enregistrerPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enregistrerPDFActionPerformed(evt);
            }
        });

        bt_enregistrerBrouillion.setText("Enregistrer comme brouillon");
        bt_enregistrerBrouillion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enregistrerBrouillionActionPerformed(evt);
            }
        });

        bt_annuler.setText("Annuler");
        bt_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_annulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_mainLayout = new javax.swing.GroupLayout(jp_main);
        jp_main.setLayout(jp_mainLayout);
        jp_mainLayout.setHorizontalGroup(
            jp_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_mainLayout.createSequentialGroup()
                .addGroup(jp_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp_mainLayout.createSequentialGroup()
                        .addGroup(jp_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_mainLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jp_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_entrepriseCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jp_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_mainLayout.createSequentialGroup()
                                            .addGroup(jp_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(lb_descriptionMission, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lb_choisirEtudiant, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(18, 18, 18)
                                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_mainLayout.createSequentialGroup()
                                            .addGroup(jp_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lb_creerClient)
                                                .addComponent(lb_CreerEtudiant)
                                                .addComponent(lb_choisirClient))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jp_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jp_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(bt_newClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(bt_newEtudiant, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jp_mainLayout.createSequentialGroup()
                                .addGap(245, 245, 245)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(254, 254, 254))
                    .addGroup(jp_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jp_mainLayout.createSequentialGroup()
                            .addComponent(bt_enregistrerPDF)
                            .addGap(78, 78, 78)
                            .addComponent(bt_enregistrerBrouillion)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_annuler))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jp_mainLayout.setVerticalGroup(
            jp_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_mainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_entrepriseCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jp_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_choisirClient)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_newClient)
                    .addComponent(lb_creerClient))
                .addGroup(jp_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_mainLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_choisirEtudiant)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jp_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_CreerEtudiant)
                            .addComponent(bt_newEtudiant))
                        .addGap(18, 18, 18)
                        .addComponent(lb_descriptionMission, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_annuler))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_mainLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_enregistrerPDF)
                            .addComponent(bt_enregistrerBrouillion))))
                .addContainerGap())
        );

        bt_deconnexion.setText("Deconnexion");
        bt_deconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deconnexionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_main, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_deconnexion, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_deconnexion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jp_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_enregistrerPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enregistrerPDFActionPerformed
        // enregistre les donnes rempli pas l'utilisateur au format PDF
        
    }//GEN-LAST:event_bt_enregistrerPDFActionPerformed

    private void bt_enregistrerBrouillionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enregistrerBrouillionActionPerformed
        // enregistre les donnee entrees dans la formulaire dans la bdd
        
    }//GEN-LAST:event_bt_enregistrerBrouillionActionPerformed

    private void bt_deconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deconnexionActionPerformed
        // retourne sur la page de connexion
        int input = JOptionPane.showConfirmDialog(this, "Quitter l'application ?","", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (input == JOptionPane.OK_OPTION) {
            deconnexion  test = new deconnexion(); //ajouter le code pour la page deconnexion
       this.setVisible(false); 
        } else if (input == JOptionPane.CANCEL_OPTION) {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_bt_deconnexionActionPerformed

    private void bt_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_annulerActionPerformed
        // retourne sur la page d'accueil
        int input = JOptionPane.showConfirmDialog(this, "Quitter l'application ?","", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (input == JOptionPane.OK_OPTION) {
            acceuil  test = new acceuil(); //ajouter code pour la page accueil
       this.setVisible(false); 
        } else if (input == JOptionPane.CANCEL_OPTION) {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_bt_annulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreationConvention.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreationConvention.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreationConvention.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreationConvention.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CreationConvention().setVisible(true);
        });

        /*try {
            Class.forName("com.mysql.jdbc.Driver");
            try (Connection co = DriverManager.getConnection("jdbc:mysql://localhost:3306/testbdd", "root", "HelloWorld")) {
                Statement stmt=co.createStatement();
                ResultSet rs=stmt.executeQuery("select * from user");
                while(rs.next())
                    System.out.println(rs.getString(1)+"  "+rs.getString(2)+"  "+rs.getString(3)+"  "+rs.getString(4)+"  "+rs.getString(5));
            }  
        }
        catch (ClassNotFoundException | SQLException e)
        {
            System.out.println(e);
        }  */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_annuler;
    private javax.swing.JButton bt_deconnexion;
    private javax.swing.JButton bt_enregistrerBrouillion;
    private javax.swing.JButton bt_enregistrerPDF;
    private javax.swing.JButton bt_newClient;
    private javax.swing.JButton bt_newEtudiant;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel jp_main;
    private javax.swing.JLabel lb_CreerEtudiant;
    private javax.swing.JLabel lb_choisirClient;
    private javax.swing.JLabel lb_choisirEtudiant;
    private javax.swing.JLabel lb_creerClient;
    private javax.swing.JLabel lb_descriptionMission;
    private javax.swing.JLabel lb_entrepriseCliente;
    // End of variables declaration//GEN-END:variables
    private DefaultComboBoxModel<String> modelCbbChoisirClient;
    private DefaultComboBoxModel<String> modelCbbChoisirEtudiant;
  

}
